import type { Viewport } from 'next'

import '@/styles/globals.css'

import { Title } from '@/components/ui'

const DEFAULT_TITLE = 'inv'

export const metadata = {
  manifest: '/manifest.json',
  description: 'Generated by create-t3-app',
  icons: {
    icon: '/favicon.png',
    shortcut: '/favicon.png',
    apple: '/icon.png',
  },
  title: DEFAULT_TITLE,
}

export const viewport: Viewport = {
  themeColor: '#193549',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <div className='flex min-h-screen flex-col bg-cb-dark-blue text-cb-white'>
          <div className='container mx-auto mb-4 flex w-full max-w-screen-md items-center px-4 pt-4 md:px-0'>
            <Title>inv</Title>
          </div>
          {children}
        </div>
      </body>
    </html>
  )
}
